apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: g6backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: g6backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: g6backend
        image: raniotitonk/subproject-backend
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
---
apiVersion: v1
kind: Service
metadata:
  name: g6backend
spec:
  selector:
    app: g6backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP